version: "3.5"
services:
  database:
    container_name: postgres_container
    image: postgres:14
  pgadmin4:
    container_name: pgadmin_container
    image: dpage/pgadmin4
  cache:
    image: redis:6.2-alpine
